name: flutter_alarmclock
description: Flutter plugin for accessing the Android AlarmClock service.
version: 0.0.1
homepage:  https://github.com/ChakibAA/Flutter_AlarmClock.git

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dz.chakib.flutter_alarmclock
        pluginClass: FlutterAlarmclockPlugin
